name: Medtrack Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 'any'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get

      - name: Generate Dummy Firebase Options
        run: |
          mkdir -p lib
          echo "import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;" > lib/firebase_options.dart
          echo "class DefaultFirebaseOptions {" >> lib/firebase_options.dart
          echo "  static FirebaseOptions get currentPlatform {" >> lib/firebase_options.dart
          echo "    return const FirebaseOptions(" >> lib/firebase_options.dart
          echo "      apiKey: 'dummy'," >> lib/firebase_options.dart
          echo "      appId: 'dummy'," >> lib/firebase_options.dart
          echo "      messagingSenderId: 'dummy'," >> lib/firebase_options.dart
          echo "      projectId: 'dummy'," >> lib/firebase_options.dart
          echo "    );" >> lib/firebase_options.dart
          echo "  }" >> lib/firebase_options.dart
          echo "}" >> lib/firebase_options.dart
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
